// Where each cabin is on the ship, for the ship GPS (directions).
//
// Data: src/pkjs/data/cabins-<SHIP>.js, generated by tools/extract_cabins.py from
// Royal's deck-plan SVGs. Positions are in metres:
//   a = metres aft of the bow (0 = bow, grows toward the stern)
//   x = metres from the centreline (negative = port, positive = starboard)
// Cabins are stored as runs, not one by one: a run is cabins in one row whose
// numbers step evenly, [first, count, step, aFirst, aLast, x]. A cabin's `a` is
// interpolated along its run (within about a metre of the deck plan).
// Each deck also lists its main stairwells as [a, x].
// The ship's two elevator banks are `banks.fwd` and `banks.aft` (same `a` on
// every deck), which is also the Fore / Mid / Aft split the venue table uses.

var DATA = {
  HM: require('./data/cabins-HM')
};

var CENTRE = 3;   // metres either side of the centreline that count as "centre"

// {deck, a, x, side, zone} for a cabin number, or null if it isn't on the plans.
function find(ship, number) {
  var t = DATA[ship];
  var n = parseInt(String(number).replace(/\D/g, ''), 10);
  if (!t || !n) {
    return null;
  }
  var decks = Object.keys(t.decks);
  for (var i = 0; i < decks.length; i++) {
    var runs = t.decks[decks[i]].runs;
    for (var j = 0; j < runs.length; j++) {
      var r = runs[j];
      var k = r[2] === 0 ? (n === r[0] ? 0 : -1) : (n - r[0]) / r[2];
      if (k >= 0 && k < r[1] && k === Math.floor(k)) {
        var a = r[1] > 1 ? r[3] + (r[4] - r[3]) * k / (r[1] - 1) : r[3];
        return place(t, parseInt(decks[i], 10), Math.round(a * 10) / 10, r[5]);
      }
    }
  }
  return null;
}

function place(t, deck, a, x) {
  return {
    deck: deck,
    a: a,
    x: x,
    side: Math.abs(x) <= CENTRE ? 'Centre' : x < 0 ? 'Port' : 'Starboard',
    zone: a < t.banks.fwd ? 'Fore' : a > t.banks.aft ? 'Aft' : 'Mid'
  };
}

// The elevator bank to use for a cabin and the walk from it:
// {bank: 'Forward'|'Aft', side, toward: 'forward'|'aft'|null, metres}.
function fromElevators(ship, where) {
  var t = DATA[ship];
  if (!t || !where) {
    return null;
  }
  var fwd = Math.abs(where.a - t.banks.fwd);
  var aft = Math.abs(where.a - t.banks.aft);
  var bankA = fwd <= aft ? t.banks.fwd : t.banks.aft;
  var d = where.a - bankA;
  var m = Math.round(Math.abs(d));
  return {
    bank: fwd <= aft ? 'Forward' : 'Aft',
    side: where.side,
    toward: m < 3 ? null : d > 0 ? 'aft' : 'forward',
    metres: m
  };
}

// Main stairwells on a deck, nearest first: [{a, x, metres}].
function stairs(ship, where) {
  var t = DATA[ship];
  var deck = t && where && t.decks[String(where.deck)];
  if (!deck) {
    return [];
  }
  return deck.stairs.map(function(s) {
    return {a: s[0], x: s[1], metres: Math.round(Math.abs(s[0] - where.a) + Math.abs(s[1] - where.x))};
  }).sort(function(p, q) { return p.metres - q.metres; });
}

module.exports = {
  find: find,
  fromElevators: fromElevators,
  stairs: stairs,
  ships: function() { return Object.keys(DATA); }
};
