// Ship map for the GPS (docs/DESIGN_V1_1.md §9): where things are on the ship and
// walking routes between them, on the walkway graph. Phone only: the watch gets
// short strings (gpstext.js) and no map data.
//
// Data (generated by tools/shipmap/, never edited by hand):
//   data/cabins-<SHIP>.js    every cabin
//   data/places-<SHIP>.js    venue spots, elevator banks, stairwells
//   data/walkways-<SHIP>.js  walkable corridors and public space as a graph, restrooms
// Every position is {deck, a, x} in metres: a = aft of the bow, x = from the
// centreline (negative = port).
//
// - Walking follows the graph: corridors that really connect, lobbies, open decks.
//   Port and starboard only meet where the graph has a real link, and a route
//   that changes side gets a {do: 'cross'} step.
// - A spot is snapped to the graph: a cabin to its corridor, a venue to the
//   nearest public path. If that can't be done confidently the answer is a reduced
//   one: {approx: true, steps: [{do: 'approx', deck, toward, metres}]}.
// - Uncertain links ('?' in the data) are used only when nothing certain connects;
//   such a route has unsure: true.
// - restroom() searches every deck, with the real cost of stairs and elevators.
// - setFlip() mirrors port and starboard for the whole ship or single decks (the
//   test-cruise setting, §9.7); it applies to every spot and to the graph.
'use strict';
var cabins = require('./cabins');

var PLACES = {
  HM: require('./data/places-HM')
};
var WALKWAYS = {
  HM: require('./data/walkways-HM')
};

var FLIP = {};             // ship -> {all: bool, decks: {deck: true}}

var SIDE_GAP = 3;          // |x| under this counts as the middle of the ship
var ELEVATOR_WAIT = 25;    // metres-equivalent for waiting + riding an elevator
var ELEVATOR_PER_DECK = 2;
var STAIRS_PER_DECK = 8;   // metres-equivalent per deck on foot
var SNAP_CABIN = 8;        // a cabin centre must be this close to a cabin corridor
var SNAP_VENUE = 18;       // a venue label centre must be this close to a public path
var SNAP_ANY = 10;         // ... or this close to any path
var LOBBY_NEAR = 12;       // a crossing this close to a bank is "at the lobby"

function sideOf(x) {
  return Math.abs(x) < SIDE_GAP ? 'Centre' : x < 0 ? 'Port' : 'Starboard';
}

// Port and starboard as the plans draw them, unless the owner flipped the ship
// or this deck (test cruise, §9.7).
function flipped(ship, deck) {
  var f = FLIP[ship];
  return !!f && !!f.all !== !!(f.decks && f.decks[deck]);
}

function X(ship, deck, x) {
  return flipped(ship, deck) ? -x : x;
}

// Flip settings: {all: bool, decks: [deck numbers]}. A deck in `decks` is flipped
// on top of `all` (so with all set, listing a deck puts it back).
function setFlip(ship, flip) {
  var decks = {};
  ((flip && flip.decks) || []).forEach(function(d) { decks[d] = true; });
  FLIP[ship] = {all: !!(flip && flip.all), decks: decks};
  delete GRAPHS[ship];
}

function pt(deck, a, x, extra) {
  var p = {deck: deck, a: a, x: x, side: sideOf(x)};
  Object.keys(extra || {}).forEach(function(k) { p[k] = extra[k]; });
  return p;
}

// Places for a venue name from the table: [{deck, a, x, side}], [] if not on the plans.
function venue(ship, name) {
  var t = PLACES[ship];
  var pts = t && t.venues[name];
  return (pts || []).map(function(p) { return pt(p[0], p[1], X(ship, p[0], p[2]), {name: name}); });
}

// Rough spot from the venue table's deck + Fore/Mid/Aft, for venues the plans don't label.
function approx(ship, deck, position) {
  var t = PLACES[ship];
  if (!t || !deck) {
    return null;
  }
  var f = t.banks.fwd.a, b = t.banks.aft.a;
  var a = position === 'Fore' ? f - 25 : position === 'Aft' ? b + 25 : (f + b) / 2;
  return pt(deck, a, 0, {approx: true});
}

function cabin(ship, number) {
  var c = cabins.find(ship, number);
  return c ? pt(c.deck, c.a, X(ship, c.deck, c.x), {cabin: String(number)}) : null;
}

// ---------------------------------------------------------------------------
// The graph: one node per walkway node on every deck, plus elevator and stair links.

var GRAPHS = {};

function graph(ship) {
  if (GRAPHS[ship]) {
    return GRAPHS[ship];
  }
  var w = WALKWAYS[ship];
  if (!w) {
    return null;
  }
  var g = {nodes: [], adj: [], index: {}, decks: {}, w: w};
  function add(deck, n) {
    var i = g.nodes.length;
    g.nodes.push({deck: deck, id: n[0], a: n[1], x: X(ship, deck, n[2]), kind: w.kinds[n[3]] || n[3]});
    g.adj.push([]);
    g.index[deck + ':' + n[0]] = i;
    return i;
  }
  function link(i, j, cost, type, q, info) {
    g.adj[i].push({to: j, cost: cost, type: type, q: !!q, info: info});
    g.adj[j].push({to: i, cost: cost, type: type, q: !!q, info: info});
  }
  Object.keys(w.decks).forEach(function(d) {
    var deck = parseInt(d, 10), dk = w.decks[d];
    dk.nodes.forEach(function(n) { add(deck, n); });
    var segs = g.decks[deck] = [];
    dk.edges.forEach(function(e, k) {
      var i = g.index[deck + ':' + e[0]], j = g.index[deck + ':' + e[1]];
      var len = Math.sqrt(sq(g.nodes[i].a - g.nodes[j].a) + sq(g.nodes[i].x - g.nodes[j].x));
      link(i, j, len, 'walk', e[2] === '?');
      segs.push({i: i, j: j, len: len, q: e[2] === '?', corridor: k < dk.nc});
    });
  });
  Object.keys(w.lobbies).forEach(function(bk) {
    var decks = Object.keys(w.lobbies[bk]).map(Number).sort(function(p, q) { return p - q; });
    var bankName = bk === 'fwd' ? 'Forward' : 'Aft';
    [0, 1].forEach(function(side) {
      for (var m = 0; m < decks.length; m++) {
        for (var n = m + 1; n < decks.length; n++) {
          var i = g.index[decks[m] + ':' + w.lobbies[bk][decks[m]][side]];
          var j = g.index[decks[n] + ':' + w.lobbies[bk][decks[n]][side]];
          if (i !== undefined && j !== undefined) {
            link(i, j, ELEVATOR_WAIT + ELEVATOR_PER_DECK * Math.abs(decks[n] - decks[m]), 'elevator', false, bankName);
          }
        }
      }
    });
  });
  w.stairs.forEach(function(s) {
    for (var k = 0; k + 1 < s[2].length; k++) {
      var i = g.index[s[2][k] + ':' + s[3][k]], j = g.index[s[2][k + 1] + ':' + s[3][k + 1]];
      if (i !== undefined && j !== undefined && s[3][k] !== null && s[3][k + 1] !== null) {
        link(i, j, STAIRS_PER_DECK * Math.abs(s[2][k + 1] - s[2][k]), 'stairs', s[5] === '?');
      }
    }
  });
  GRAPHS[ship] = g;
  return g;
}

function sq(v) { return v * v; }

// Nearest point of a deck's paths to a spot. kind: 'cabin' | 'venue'.
// Returns {seg, t, foot: {a, x}, off, q} or null when it can't be done confidently.
function snap(ship, p, kind, allowQ) {
  var g = graph(ship);
  if (!g || !p || p.approx || !g.decks[p.deck]) {
    return null;
  }
  function best(filter, limit) {
    var b = null;
    g.decks[p.deck].forEach(function(s) {
      if ((s.q && !allowQ) || !filter(s)) {
        return;
      }
      var A = g.nodes[s.i], B = g.nodes[s.j];
      var da = B.a - A.a, dx = B.x - A.x, L2 = da * da + dx * dx;
      var t = L2 ? ((p.a - A.a) * da + (p.x - A.x) * dx) / L2 : 0;
      t = Math.max(0, Math.min(1, t));
      var fa = A.a + da * t, fx = A.x + dx * t;
      var off = Math.sqrt(sq(fa - p.a) + sq(fx - p.x));
      if (off <= limit && (!b || off < b.off)) {
        b = {seg: s, t: t, foot: {a: fa, x: fx}, off: off, q: s.q};
      }
    });
    return b;
  }
  if (kind === 'cabin') {
    return best(function(s) { return s.corridor; }, SNAP_CABIN);
  }
  return best(function(s) { return !s.corridor; }, SNAP_VENUE) || best(function() { return true; }, SNAP_ANY);
}

// Dijkstra from a snapped spot over the whole ship (or one deck). Returns {dist, prev}.
function search(g, from, sn, allowQ, onlyDeck) {
  var n = g.nodes.length, dist = new Array(n), prev = new Array(n), done = new Array(n);
  for (var k = 0; k < n; k++) { dist[k] = Infinity; }
  var s = sn.seg;
  dist[s.i] = sn.off + s.len * sn.t; prev[s.i] = {start: true};
  dist[s.j] = Math.min(dist[s.j], sn.off + s.len * (1 - sn.t));
  if (dist[s.j] === sn.off + s.len * (1 - sn.t)) { prev[s.j] = {start: true}; }
  // Simple O(n^2) Dijkstra: a few hundred nodes, run on the phone on request.
  for (;;) {
    var u = -1;
    for (var m = 0; m < n; m++) {
      if (!done[m] && dist[m] < Infinity && (u === -1 || dist[m] < dist[u])) { u = m; }
    }
    if (u === -1) { break; }
    done[u] = true;
    g.adj[u].forEach(function(e) {
      if ((e.q && !allowQ) || (onlyDeck !== undefined && e.type !== 'walk')) {
        return;
      }
      var c = dist[u] + e.cost;
      if (c < dist[e.to]) {
        dist[e.to] = c;
        prev[e.to] = {from: u, edge: e};
      }
    });
  }
  return {dist: dist, prev: prev};
}

// Best way from the search to a snapped target: {cost, end: node index | -1 (same segment)}.
function reach(res, sFrom, sTo) {
  var s = sTo.seg, best = null;
  [[s.i, s.len * sTo.t], [s.j, s.len * (1 - sTo.t)]].forEach(function(o) {
    var c = res.dist[o[0]] + o[1] + sTo.off;
    if (c < Infinity && (!best || c < best.cost)) {
      best = {cost: c, end: o[0]};
    }
  });
  if (sFrom.seg === s) {   // both on one segment: walk straight along it
    var c = sFrom.off + s.len * Math.abs(sFrom.t - sTo.t) + sTo.off;
    if (!best || c <= best.cost) {
      best = {cost: c, end: -1};
    }
  }
  return best;
}

// Rebuild the list of points / rides from the start to node `end`.
function trail(g, res, end) {
  var seq = [];
  var k = end;
  while (k !== undefined && k !== -1) {
    var p = res.prev[k];
    seq.unshift({node: k, via: p && p.edge ? p.edge : null});
    if (!p || p.start) { break; }
    k = p.from;
  }
  return seq;
}

function planOne(ship, from, targets, allowQ) {
  var g = graph(ship);
  var sFrom = snap(ship, from, from.cabin ? 'cabin' : 'venue', allowQ);
  if (!sFrom) {
    return null;
  }
  var res = search(g, from, sFrom, allowQ);
  var best = null;
  targets.forEach(function(q) {
    var sTo = snap(ship, q, q.cabin ? 'cabin' : 'venue', allowQ);
    if (!sTo) {
      return;
    }
    var r = reach(res, sFrom, sTo);
    if (r && (!best || r.cost < best.cost)) {
      best = {cost: r.cost, end: r.end, q: q, sTo: sTo};
    }
  });
  if (!best) {
    return null;
  }
  var seq = best.end === -1 ? [] : trail(g, res, best.end);
  return {cost: best.cost, from: from, to: best.q, sFrom: sFrom, sTo: best.sTo, seq: seq, g: g};
}

// Points on one deck -> walk / cross steps.
function walkSteps(pts, deck, toLabel) {
  var steps = [], legStart = 0;
  var metres = function(i, j) {
    var m = 0;
    for (var k = i; k < j; k++) { m += Math.sqrt(sq(pts[k + 1].a - pts[k].a) + sq(pts[k + 1].x - pts[k].x)); }
    return m;
  };
  function walk(i, j, label) {
    var da = pts[j].a - pts[i].a, m = metres(i, j);
    if (m < 0.5) { return; }
    var side = 'Centre';
    for (var k = j; k >= i && side === 'Centre'; k--) { side = sideOf(pts[k].x); }
    if (label && sideOf(pts[j].x) === 'Centre') { side = 'Centre'; }   // ends mid-ship
    steps.push({do: 'walk', deck: deck, toward: Math.abs(da) < 3 ? null : da > 0 ? 'aft' : 'forward',
      metres: Math.round(m), crossAt: null, side: side, to: label || null});
  }
  // A change of side (ignoring the centre band) becomes a cross step. The walk up to
  // the first centre point (or the last point on the old side) comes before it; the
  // transverse part and anything after belongs to the next walk.
  var lastSide = null, lastIdx = 0;
  for (var k = 0; k < pts.length; k++) {
    var s = sideOf(pts[k].x);
    if (s === 'Centre') { continue; }
    if (lastSide && s !== lastSide) {
      var at = lastIdx + 1 < k ? lastIdx + 1 : lastIdx;
      walk(legStart, at);
      steps.push({do: 'cross', deck: deck, from: lastSide, to: s, at: crossName(pts[at].a), a: Math.round(pts[at].a)});
      legStart = at;
    }
    lastSide = s; lastIdx = k;
  }
  walk(legStart, pts.length - 1, toLabel);
  return steps;
}

var BANK_A = {Forward: 115.8, Aft: 239.3};
function crossName(a) {
  if (Math.abs(a - BANK_A.Forward) < LOBBY_NEAR) { return 'Forward lobby'; }
  if (Math.abs(a - BANK_A.Aft) < LOBBY_NEAR) { return 'Aft lobby'; }
  return a < BANK_A.Forward ? 'forward' : a > BANK_A.Aft ? 'aft' : 'midships';
}

// A plan -> {metres, steps}.
function stepsOf(plan) {
  var g = plan.g, steps = [], pts = [{a: plan.from.a, x: plan.from.x}, plan.sFrom.foot], deck = plan.from.deck;
  plan.seq.forEach(function(s) {
    var n = g.nodes[s.node];
    if (s.via && s.via.type !== 'walk') {
      var prevNode = pts[pts.length - 1];
      steps = steps.concat(walkSteps(pts, deck, s.via.type === 'elevator' ? s.via.info + ' elevators' : 'stairs'));
      var from = deck;
      if (s.via.type === 'elevator') {
        steps.push({do: 'elevator', bank: s.via.info, from: from, to: n.deck});
      } else {
        steps.push({do: 'stairs', up: n.deck > from, decks: Math.abs(n.deck - from), from: from, to: n.deck, a: Math.round(n.a)});
      }
      deck = n.deck;
      pts = [{a: prevNode.a, x: prevNode.x}];
      pts[0] = {a: n.a, x: n.x};
    } else {
      pts.push({a: n.a, x: n.x});
    }
  });
  pts.push(plan.sTo.foot);
  pts.push({a: plan.to.a, x: plan.to.x});
  steps = steps.concat(walkSteps(pts, deck, plan.to.name || null));
  // Merge rides of one bank (e.g. two elevator hops) and drop short walks.
  var out = [];
  steps.forEach(function(s) {
    var last = out[out.length - 1];
    if (last && s.do === 'elevator' && last.do === 'elevator' && last.bank === s.bank) {
      last.to = s.to;
      return;
    }
    if (last && s.do === 'stairs' && last.do === 'stairs') {
      last.to = s.to; last.up = s.to > last.from; last.decks = Math.abs(s.to - last.from);
      return;
    }
    out.push(s);
  });
  out = out.filter(function(s) { return s.do !== 'walk' || s.metres >= 3; });
  var metres = out.reduce(function(n, s) { return n + (s.do === 'walk' ? s.metres : 0); }, 0);
  return {metres: metres, steps: out};
}

function approxRoute(from, q) {
  var da = q.a - from.a;
  var m = Math.round(Math.sqrt(sq(da) + sq(q.x - from.x)));
  var toward = Math.abs(da) < 3 ? null : da > 0 ? 'aft' : 'forward';
  return {approx: true, metres: m, deck: q.deck, toward: toward,
    steps: [{do: 'approx', deck: q.deck, from: from.deck, toward: toward, metres: m, side: q.side, to: q.name || null}]};
}

// Route between two spots ({deck, a, x}). `to` can be a list (a venue with several
// spots): the cheapest one wins. Returns {metres, steps[, unsure][, approx]} or null.
function route(ship, from, to) {
  var t = PLACES[ship];
  if (!t || !WALKWAYS[ship] || !from || !to) {
    return null;
  }
  var targets = [].concat(to).filter(Boolean);
  if (!targets.length) {
    return null;
  }
  var plan = planOne(ship, from, targets, false), unsure = false;
  if (!plan) {
    plan = planOne(ship, from, targets, true);
    unsure = !!plan;
  }
  if (!plan) {
    // Reduced answer: deck + fore/aft + straight distance to the nearest spot.
    var near = targets.slice().sort(function(p, q) {
      return (Math.abs(p.deck - from.deck) * 10 + Math.abs(p.a - from.a)) - (Math.abs(q.deck - from.deck) * 10 + Math.abs(q.a - from.a));
    })[0];
    return approxRoute(from, near);
  }
  var r = stepsOf(plan);
  if (unsure) {
    r.unsure = true;
  }
  r.cost = Math.round(plan.cost);
  r.to = plan.to;
  return r;
}

// Walking metres between two spots on one deck along the walkways, or null when
// the deck's walkways don't join them (or a spot can't be snapped).
function walkMetres(ship, p, q) {
  if (!p || !q || p.deck !== q.deck) {
    return null;
  }
  var g = graph(ship);
  for (var pass = 0; pass < 2; pass++) {
    var sp = snap(ship, p, p.cabin ? 'cabin' : 'venue', !!pass), sq2 = snap(ship, q, q.cabin ? 'cabin' : 'venue', !!pass);
    if (!sp || !sq2) {
      continue;
    }
    var r = reach(search(g, p, sp, !!pass, p.deck), sp, sq2);
    if (r) {
      return Math.round(r.cost);
    }
  }
  return null;
}

// Closest restroom anywhere on the ship, by real route cost (stairs and elevators
// included). opts: {gender: 'm' | 'w', all: true to include the kids'-area ones}.
// Returns {deck, a, x, g, metres (walking), cost, route} or null.
function restroom(ship, from, opts) {
  opts = opts || {};
  var g = graph(ship), w = WALKWAYS[ship];
  if (!g || !from) {
    return null;
  }
  var list = [];
  Object.keys(w.restrooms).forEach(function(d) {
    w.restrooms[d].forEach(function(r) {
      if ((r[4] === 'kids' && !opts.all) || (opts.gender && r[3].indexOf(opts.gender) === -1 && r[3] !== 'mw?')) {
        return;
      }
      var deck = parseInt(d, 10);
      list.push(pt(deck, r[0], X(ship, deck, r[1]), {name: 'Restroom', g: r[3], node: r[2]}));
    });
  });
  var best = null;
  [false, true].some(function(allowQ) {
    var sFrom = snap(ship, from, from.cabin ? 'cabin' : 'venue', allowQ);
    if (!sFrom) {
      return false;
    }
    var res = search(g, from, sFrom, allowQ);
    list.forEach(function(r) {
      var k = g.index[r.deck + ':' + r.node];
      var foot = g.nodes[k];
      var off = Math.sqrt(sq(foot.a - r.a) + sq(foot.x - r.x));
      var c = res.dist[k] + off;
      if (c < Infinity && (!best || c < best.cost)) {
        best = {r: r, cost: c, end: k, off: off, sFrom: sFrom, res: res, q: allowQ};
      }
    });
    return !!best;
  });
  if (!best) {
    // Nothing reachable: the old same-deck answer, as a straight-line guess.
    var same = list.filter(function(r) { return r.deck === from.deck; }).map(function(r) {
      return {r: r, m: Math.abs(r.a - from.a) + Math.abs(r.x - from.x)};
    }).sort(function(p, q) { return p.m - q.m; })[0];
    return same ? {deck: same.r.deck, a: same.r.a, x: same.r.x, g: same.r.g, metres: Math.round(same.m), approx: true,
      route: approxRoute(from, same.r)} : null;
  }
  var foot = g.nodes[best.end];
  var plan = {g: g, from: from, to: best.r, sFrom: best.sFrom, sTo: {foot: {a: foot.a, x: foot.x}},
    seq: trail(g, best.res, best.end), cost: best.cost};
  var r = stepsOf(plan);
  if (best.q) {
    r.unsure = true;
  }
  return {deck: best.r.deck, a: best.r.a, x: best.r.x, g: best.r.g, metres: r.metres, cost: Math.round(best.cost),
    unsure: best.q || undefined, route: r};
}

module.exports = {
  venue: venue,
  approx: approx,
  cabin: cabin,
  restroom: restroom,
  route: route,
  walkMetres: walkMetres,
  data: function(ship) { return PLACES[ship] || null; },
  walkways: function(ship) { return WALKWAYS[ship] || null; },
  setFlip: setFlip,
  flipped: flipped,
  banks: function(ship) { return PLACES[ship] ? {fwd: PLACES[ship].banks.fwd.a, aft: PLACES[ship].banks.aft.a} : null; },
  _snap: snap   // for tests
};
