// Offline voice commands (docs/DESIGN_V1_1.md §9.6, brief item 29).
//
// The watch records, the Pebble app turns speech into text on the phone (no
// internet at sea), and this module turns that text into one command:
//   parse(text, opts) -> {intent, A, B, cabin, A_target, B_target, A_how, B_how,
//                         reason?, topic?, deck?, via?, A_spot?, atA?}
//   A_spot: 'group' | 'multi_spot' | 'ashore' when A isn't one spot (no start);
//   atA: A came from "I'm at" (it also sets the spoken start, D4).
//   opts.ship     ship code (default 'HM'), picks the lexicon
//   opts.isCabin  function(number string) -> true when it's a cabin on the
//                 plans; index.js passes cabins.find, tests pass a made-up list
//
// Two parts, one owner each:
// - GRAMMAR (below, hand-edited): command words, restroom / elevator / stairs /
//   cabin words, numbers. Nothing ship-specific.
// - The venue lexicon (src/pkjs/data/voice-<SHIP>.js, generated by
//   tools/voice/build_voice.js from tools/voice/venue-mishearings-<SHIP>.json):
//   every venue name, alias and likely mishearing. Never add venue words here.
//
// Intents: SET_LOCATION, ROUTE (via 'snack' for a bite: Cafe Promenade), ROUTE_COMBINED,
// CLOSEST_RESTROOM, CLOSEST_BAR, CLOSEST_COFFEE,
// LOCATION_REFUSED (reason restroom | bar | coffee | elevator | stairs | deck | multi_spot |
// ashore | group), OUT_OF_SCOPE_KNOWN (topic schedule | hours | stateroom), INCOMPLETE,
// NO_MATCH (reason no_command | no_place | not_mapped | empty).
// A and B are spans or tokens: @mycabin, @cabin:N, @restroom, @elevator,
// @forelev, @aftelev, @stairs, @deck:N. A null A means the current start (9.4).
// A target with '|' is a group ("Arcade|Video Arcade"): as B, route to the
// nearest member; as a spoken location it is refused (reason group).
// Every result goes to the Heard/Matched confirm screen before anything happens.
// ES5, no dependencies besides the lexicon.
'use strict';

var DATA = {
  HM: require('./data/voice-HM')
};

// ------------------------------------------------------------------ grammar

var GRAMMAR = {
  contractions: [
    ['^(?:were|we re|weare|aim|am) (?=at |in |on |near |by |next |outside |inside |back |here |sitting |standing )', 'iam '],
    ['(?:^| )(?:im|i am|i m|we are)(?= |$)', ' iam'], ['iam add(?= )', 'iam at'], ['iam and the(?= )', 'iam at the'],
    ['(?:^| )wheres(?= |$)', ' where is'], ['(?:^| )whats(?= |$)', ' what is'], ['(?:^| )whens(?= |$)', ' when is'],
    ['(?:^| )howd(?= |$)', ' how do'], ['(?:^| )wanna(?= |$)', ' want to'], ['(?:^| )gotta(?= |$)', ' have to'],
    ['(?:^| )lets(?= |$)', ' let us'], ['(?:^| )id like(?= |$)', ' i would like']
  ],
  corrections: ['no wait', 'wait no', 'no no', 'or rather', 'scratch that', 'make that', 'i meant', 'i mean', 'sorry',
    'actually', 'no', 'wait'],
  fillers: ['hey pebble', 'ok pebble', 'okay pebble', 'hi pebble', 'pebble', 'hey there', 'can you please tell me',
    'can you tell me', 'could you tell me', 'would you tell me', 'will you tell me', 'can you please', 'could you please',
    'i want to know', 'i would like to know', 'i was wondering', 'do you know', 'tell me', 'quick question', 'real quick',
    'excuse me', 'thank you', 'thanks', 'please', 'help me', 'can you', 'could you', 'would you', 'will you', 'can u',
    'on the ship', 'on this ship', 'on board', 'onboard', 'um', 'umm', 'uh', 'uhh', 'uhm', 'er', 'erm', 'ah', 'ahh', 'hmm',
    'hm', 'mm', 'oh', 'o', 'hey', 'hi', 'hello', 'ok', 'okay', 'alright', 'all right', 'so', 'well', 'just', 'kindly',
    'yeah', 'yes', 'again'],
  // Category words (regex sources). Restrooms first, so "rest room" never
  // becomes "the room". "closest restaurant" is a common mishearing of
  // "closest restroom" and there is no restaurant category.
  restroom: '(?:mens|womens|ladies|ladys|public|mens and womens)? ?(?:rest ?rooms?|bath ?rooms?|toilets?|loo|wash ?rooms?|' +
    'lavatory|lavatories|powder room|potty|wc|w c)|(?:mens|womens|ladies|ladys|gents) room|' +
    '(?:closest|nearest) restaurants?|(?:the|nearest|closest) (?:head|gents|ladies)(?! to| over| back| room| of)',
  elevatorFore: '(?:fore|forward|front|bow|four|for|4) (?:elevator|elevators|lift|lifts)(?: bank| lobby)?',
  elevatorAft: '(?:aft|after|back|rear|stern|aught) (?:elevator|elevators|lift|lifts)(?: bank| lobby)?',
  elevator: '(?:elevator|elevators|lift|lifts|elevate her|elevated her|elevate or)(?: bank| banks| lobby| lobbies)?',
  stairs: '(?:fore |forward |aft |after |back |mid |middle |midship |main )?(?:stairs|stair|stares|stairway|stairways|' +
    'staircase|staircases|stair case|stairwell|stairwells)',
  cabinWords: '(?:cabin|cabins|cabinet|cab in|cabbin|stateroom|state room|room|kevin|suite)',
  myCabin: '(?:my|our|the|this) (?:cabin|cabinet|cab in|cabbin|kevin|stateroom|state room|room|suite)|(?:my |back )?home|' +
    'cabin|stateroom|cabinet',
  here: 'right here|here|this place|this spot|where iam at|where iam now|where iam|where we are|my current location|' +
    'my location|current location|my spot',
  locationAdverbs: ['currently', 'now', 'right', 'just', 'still', 'standing', 'sitting', 'hanging out', 'waiting', 'over',
    'up', 'down', 'back', '@here'],
  locationPreps: ['in front of', 'next to', 'close to', 'outside of', 'inside of', 'across from', 'outside', 'inside',
    'beside', 'behind', 'around', 'near', 'by', 'at', 'in', 'on'],
  locationOther: ['^(?:set |change |update )?@here(?: is| to| as)? (.+)$',
    '^(?:my location is|my current location is|set (?:my )?(?:location|start)(?: to| as)?|start (?:from|at)|' +
    'routes? starts? (?:from|at)|use (.+) as (?:my )?start(?:ing point)?)\\s*(.*)$'],
  routeTriggers: [
    'how (?:do|can|could|should|would|will|shall|did) (?:i|we|you|one) (?:get|go|walk|reach|find|make it|find my way|' +
    'find our way)(?: back| over| up| down)?',
    'how (?:to|would i|i) (?:get|go|walk)(?: back)?', 'how get(?: back)?', 'how far(?: away)?(?: is it)?(?: is| to)?',
    'how (?:many|much) (?:steps|meters|metres|feet|minutes)(?: is it)?(?: to)?',
    'how long(?: does it take| will it take| is the walk| would it take)?(?: to walk| to get)?',
    'which way(?: is| to| do i go)?',
    'what is the (?:best |quickest |fastest |shortest |easiest )?(?:way|route|path)(?: to get| to go)?',
    '(?:best|quickest|fastest|shortest|easiest) (?:way|route)(?: to get| to go)?',
    'where (?:can|do|would|could) (?:i|we) find', 'where (?:is|are)', '(?:give me |get |show me |i need |i want )?directions?',
    'show (?:me|us)(?: the way| how to get| how to go)?',
    '(?:route|navigate|guide|lead|walk|take|get|bring|point|send|steer) (?:me|us)(?: back)?', 'route', 'navigate',
    '(?:i|we) (?:want|need|would like|have|got|wanna|gotta) (?:to )?(?:go|get|be|head|walk)(?: back)?',
    'iam (?:going|heading|headed|walking|trying to get|trying to go|trying to find|looking for|on my way|on our way)(?: back)?',
    '(?:going|heading|headed|on my way|on our way)(?: back)?', 'let us (?:go|head|walk)', 'what (?:deck|floor) is',
    'which (?:deck|floor) is', 'can (?:i|we) get', '(?:i|we) (?:want|need|would like)',
    '(?:go|get|head|walk|find|locate|search for)(?: back)?', 'where(?= the | a )'
  ],
  whereTriggers: ['where(?= the | a )', 'where (?:is|are)', 'where (?:can|do|would|could) (?:i|we) find',
    'what (?:deck|floor) is', 'which (?:deck|floor) is'],
  backTriggers: ['how (?:do|can) (?:i|we) get back', 'take (?:me|us) back', 'get (?:me|us) back', 'go back'],
  clauseStarters: ['how do', 'how can', 'how to get', 'how far', 'where is', 'where are', 'which way', 'take me', 'take us',
    'get me', 'bring me', 'directions', 'navigate', 'show me', 'iam at', 'iam in', 'iam on', 'iam near', 'iam by',
    'what is next', 'when is', 'closest', 'nearest', 'i want to', 'i need to', 'we want to', 'want to go', 'can i get',
    'iam going', 'iam heading', 'going to', 'heading to'],
  schedule: ['what is (?:next|on|happening|going on|up next|coming up|scheduled|playing|showing|after this)',
    '(?:^| )(?:next event|next show|up next|whats up next)(?: |$)', 'what (?:time|day) (?:is|does|do|are|s)',
    '(?:^| )when (?:is|are|does|do|will|s)(?: |$)', '(?:^| )what (?:shows|events|activities)(?: |$)',
    '(?:^| )anything (?:on|happening|fun|to do)(?: |$)',
    '(?:tonight|today|tomorrow)s? (?:schedule|show|shows|events|activities|lineup)',
    '(?:^| )(?:schedule|agenda|itinerary|all aboard|what can (?:i|we) do|what should (?:i|we) do)(?: |$)',
    '(?:^| )is there (?:a |any )?(?:show|trivia|party|event|bingo|movie)'],
  hours: ['(?:^| )(?:when|what time) (?:does|do|is|will) .*(?:open|close|closing|opening)(?: |$)',
    '(?:^| )is .* (?:open|closed)(?: |$)', '(?:^| )(?:opening hours|hours)(?: |$)'],
  stateroom: ['^@mycabin (?:number )?(?:is|=)', '^(?:set|change|update) @mycabin', '^my @cabin'],
  // Unmatched text with one of these is an event question (Not yet), not a place.
  eventWords: ['show', 'shows', 'trivia', 'bingo', 'party', 'parade', 'comedy', 'comedian', 'movie', 'film', 'class',
    'lesson', 'seminar', 'karaoke', 'concert', 'performance', 'dinner', 'lunch', 'breakfast', 'brunch', 'game', 'games',
    'tournament', 'auction', 'tour', 'meeting', 'meetup', 'meet and greet', 'dance', 'music', 'band', 'happy hour',
    'sail away', 'tasting', 'headliner', 'screening', 'deck party', 'mamma mia', 'diving show', 'cats', 'hairspray',
    'grease', 'event'],
  leadStrip: ['the', 'a', 'an', 'that', 'this', 'closest', 'nearest', 'the closest', 'the nearest', 'any', 'some'],
  tailStrip: ['please', 'located', 'is', 'on', 'at', 'now', 'again', 'is located', 'is at', 'at the moment', 'right now',
    'from here', 'from @here'],
  // Words around a venue name that don't change which venue it is
  // ("the Cartier store", "Solarium to"): the matcher may ignore them.
  noise: ['please', 'now', 'area', 'place', 'again', 'there', 'located', 'store', 'shop', 'restaurant', 'one', 'a', 'an',
    'to', 'is', 'on', 'at', 'are', 'or', 'and', 'it', 'please']
};

// ------------------------------------------------------------------ helpers

function trim(s) {
  return String(s).replace(/\s+/g, ' ').replace(/^ | $/g, '');
}

function esc(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Whole-word regex over phrases (longest first) or over a regex source.
function wordsRx(list, flags) {
  var l = list.slice().sort(function(a, b) { return b.length - a.length; });
  return srcRx(l.map(esc).join('|'), flags);
}

function srcRx(src, flags) {
  return new RegExp('(^| )(?:' + src + ')(?= |$)', flags === undefined ? 'g' : flags);
}

function startRx(list, end) {
  return list.map(function(s) { return new RegExp('^(?:' + s + ')' + (end || '(?= |$)')); });
}

function anyTest(list, s) {
  for (var i = 0; i < list.length; i++) {
    if (list[i].test(s)) {
      return true;
    }
  }
  return false;
}

function copy(o) {
  var c = {};
  Object.keys(o).forEach(function(k) { c[k] = o[k]; });
  return c;
}

var G = GRAMMAR;
var RX = {
  filler: wordsRx(G.fillers),
  correction: wordsRx(G.corrections, ''),
  correctionStart: new RegExp('^(?:' + G.corrections.map(esc).join('|') + ')(?: |$)'),
  restroom: srcRx(G.restroom),
  fore: srcRx(G.elevatorFore),
  aft: srcRx(G.elevatorAft),
  elevator: srcRx(G.elevator),
  stairs: srcRx(G.stairs),
  myCabin: srcRx(G.myCabin),
  here: srcRx(G.here),
  route: startRx(G.routeTriggers),
  where: startRx(G.whereTriggers),
  back: startRx(G.backTriggers, '$'),
  schedule: G.schedule.map(function(s) { return new RegExp(s); }),
  hours: G.hours.map(function(s) { return new RegExp(s); }),
  stateroom: G.stateroom.map(function(s) { return new RegExp(s); }),
  event: wordsRx(G.eventWords, ''),
  starter: new RegExp(' (?:(?:and|so|but|then) )?(?=(?:' + G.clauseStarters.map(esc).join('|') + ')(?: |$))', 'g'),
  locOther: G.locationOther.map(function(s) { return new RegExp(s); }),
  contractions: G.contractions.map(function(p) { return [new RegExp(p[0], 'g'), p[1]]; })
};
var LEAD = G.leadStrip.slice().sort(function(a, b) { return b.length - a.length; });
var TAIL = G.tailStrip.slice().sort(function(a, b) { return b.length - a.length; });
var NOISE = {};
G.noise.forEach(function(w) { NOISE[w] = true; });

// ------------------------------------------------------------------ numbers

var UNITS = {zero: 0, oh: 0, o: 0, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9};
var TEENS = {ten: 10, eleven: 11, twelve: 12, thirteen: 13, fourteen: 14, fifteen: 15, sixteen: 16, seventeen: 17,
  eighteen: 18, nineteen: 19};
var TENS = {twenty: 20, thirty: 30, forty: 40, fifty: 50, sixty: 60, seventy: 70, eighty: 80, ninety: 90};
var CONNECT = {to: '2', too: '2', 'for': '4'};  // may be a digit inside a run of numbers
var NO_TO_BEFORE = {deck: 1, room: 1, level: 1, floor: 1, cabin: 1, stateroom: 1, number: 1, suite: 1};

function isNumWord(w) {
  return /^\d+$/.test(w) || (w in TEENS) || (w in TENS) || w === 'hundred' || w === 'thousand' ||
    ((w in UNITS) && w !== 'oh' && w !== 'o');
}

// The words of one run of numbers -> digit groups, some marked as a possible
// "to"/"for": [{d: '89'}, {sep: 'to', d: '2'}, ...]. Spoken groups are joined
// later ("eighty-nine twenty-four" -> 89, 24 -> 8924).
function runGroups(words) {
  var out = [];
  var cur = null, scale = false, tensOpen = false;
  function flush() {
    if (cur !== null) {
      out.push({d: String(cur)});
    }
    cur = null; scale = false; tensOpen = false;
  }
  words.forEach(function(w) {
    if (/^\d+$/.test(w)) {
      flush(); out.push({d: w});
    } else if (w in CONNECT) {
      flush(); out.push({sep: w === 'for' ? 'for' : 'to', d: CONNECT[w]});
    } else if (w in UNITS) {
      var v = UNITS[w];
      if (cur !== null && (tensOpen || scale) && v > 0) {
        cur += v; tensOpen = false; scale = false;
      } else {
        flush(); cur = v;
      }
    } else if (w in TEENS) {
      if (cur !== null && scale) {
        cur += TEENS[w]; scale = false;
      } else {
        flush(); cur = TEENS[w];
      }
    } else if (w in TENS) {
      if (cur !== null && scale) {
        cur += TENS[w];
      } else {
        flush(); cur = TENS[w];
      }
      tensOpen = true; scale = false;
    } else if (w === 'hundred') {
      cur = cur === null ? 100 : Math.floor(cur / 1000) * 1000 + (cur % 1000) * 100;
      scale = true; tensOpen = false;
    } else if (w === 'thousand') {
      cur = (cur === null ? 1 : cur) * 1000; scale = true; tensOpen = false;
    }
  });
  flush();
  return out;
}

// Real cabins count most, then 4-5 digit numbers; each "to" costs a little.
function chunkScore(chunks, isCabin, deckCtx) {
  var score = 0;
  chunks.forEach(function(c, j) {
    if (j === 0 && deckCtx && c.length <= 2) {
      score += 10;
    } else if (isCabin(c)) {
      score += 10;
    } else if (c.length === 4 || c.length === 5) {
      score += 1;
    }
  });
  return score - (chunks.length - 1) * 0.5;
}

// Picks digit-or-word for each possible separator: "8924 to 6902", "8924".
function chooseReading(groups, isCabin, deckCtx) {
  var opt = [];
  groups.forEach(function(g, i) {
    if (g.sep) {
      opt.push(i);
    }
  });
  var n = Math.min(opt.length, 6);
  var best = null;
  for (var mask = 0; mask < (1 << n); mask++) {
    var chunks = [''], seps = [], ok = true;
    for (var i = 0; i < groups.length && ok; i++) {
      var k = opt.indexOf(i);
      if (k !== -1 && k < n && (mask & (1 << k))) {
        ok = chunks[chunks.length - 1] !== '';
        seps.push(groups[i].sep);
        chunks.push('');
      } else {
        chunks[chunks.length - 1] += groups[i].d;
      }
    }
    if (ok && chunks[chunks.length - 1] !== '') {
      var score = chunkScore(chunks, isCabin, deckCtx);
      if (!best || score > best.score) {
        best = {score: score, chunks: chunks, seps: seps};
      }
    }
  }
  if (!best) {
    return {text: groups.map(function(g) { return g.d; }).join(''), score: 0};
  }
  var s = best.chunks[0];
  for (var j = 0; j < best.seps.length; j++) {
    s += ' ' + best.seps[j] + ' ' + best.chunks[j + 1];
  }
  return {text: s, score: best.score};
}

// Number words -> digits in one clause, deciding "to"/"two" by the cabin list.
function numbers(clause, isCabin) {
  var w = clause.split(' ');
  var out = [];
  var i = 0;
  function num(j) {
    if (j < 0 || j >= w.length) {
      return false;
    }
    return isNumWord(w[j]) || ((w[j] === 'oh' || w[j] === 'o') && (isNumWord(w[j - 1] || '') || isNumWord(w[j + 1] || '')));
  }
  while (i < w.length) {
    if (!num(i)) {
      out.push(w[i]);
      i++;
      continue;
    }
    var run = [];
    while (i < w.length && (num(i) || ((w[i] in CONNECT) && run.length && num(i + 1)))) {
      run.push(w[i]);
      i++;
    }
    var before = out.length ? out[out.length - 1] : '';
    var deckCtx = before === 'deck';
    var more = i < w.length;
    var groups = runGroups(run);
    var last = groups[groups.length - 1];
    if (more && last && !last.sep && last.d === '2' && groups.length > 1) {
      // A final "two" before more words may be "to": "8924 two the Solarium".
      var withTwo = chooseReading(groups, isCabin, deckCtx);
      var without = chooseReading(groups.slice(0, -1), isCabin, deckCtx);
      if (without.score - 0.5 > withTwo.score) {
        out.push(without.text, 'to');
      } else {
        out.push(withTwo.text);
      }
    } else if (more && groups.length === 1 && /^\d{5,6}$/.test(last.d) && /2$/.test(last.d) &&
               !isCabin(last.d) && isCabin(last.d.slice(0, -1))) {
      out.push(last.d.slice(0, -1), 'to');  // "89242 the Solarium": a "to" glued on
    } else if (groups.length === 1 && last.d === '2' && run.length === 1 &&
               out.length && more && !(before in NO_TO_BEFORE)) {
      out.push('to');  // a lone "two" between words
    } else if (last.sep) {
      out.push(chooseReading(groups.slice(0, -1), isCabin, deckCtx).text, 'to');
    } else {
      out.push(chooseReading(groups, isCabin, deckCtx).text);
    }
  }
  return out.join(' ');
}

// ------------------------------------------------------------------ normalise

// The shared first steps for transcripts and lexicon phrases: lowercase, no
// accents, & -> and, digit punctuation, no apostrophes, "(Ages 6-12)" dropped.
function clean(raw) {
  return String(raw || '').replace(/[\u2018\u2019\u02bc`]/g, "'").replace(/[\u201c\u201d]/g, '"')
    .replace(/[\u00e9\u00e8]/g, 'e').toLowerCase()
    .replace(/\(ages[^)]*\)/g, ' ')
    .replace(/(\d),(?=\d{3}(?:\D|$))/g, '$1').replace(/(\d)-(?=\d)/g, '$1 ').replace(/#\s*(?=\d)/g, '')
    .replace(/&/g, ' and ').replace(/([a-z])-(?=[a-z])/g, '$1 ');
}

function words(s) {
  return trim(s.replace(/'/g, '').replace(/[^a-z0-9@ ]+/g, ' '));
}

function stripFillers(s) {
  var prev;
  do {
    prev = s;
    s = trim(s.replace(RX.filler, '$1'));
  } while (s !== prev);
  return s;
}

// Category words -> tokens (order matters, see GRAMMAR).
function categories(s, isCabin) {
  var cw = G.cabinWords;
  s = ' ' + s + ' ';
  s = s.replace(RX.restroom, '$1@restroom');
  s = s.replace(RX.fore, '$1@forelev').replace(RX.aft, '$1@aftelev').replace(RX.elevator, '$1@elevator');
  s = s.replace(RX.stairs, '$1@stairs');
  s = s.replace(new RegExp(' deck (\\d{1,2}) ' + cw + ' (?:number )?(\\d{3})(?= )', 'g'), function(m, d, n) {
    return isCabin(d + n) ? ' @cabin:' + d + n : m;
  });
  s = s.replace(new RegExp(' ' + cw + ' (?:number )?(\\d{3}) on deck (\\d{1,2})(?= )', 'g'), function(m, n, d) {
    return isCabin(d + n) ? ' @cabin:' + d + n : m;
  });
  s = s.replace(new RegExp(' (?:' + cw + ') (?:number |no |is )?(\\d{3,5})(?= )', 'g'), ' @cabin:$1');
  s = s.replace(/ (\d{4,5})(?= )/g, function(m, n) { return isCabin(n) ? ' @cabin:' + n : m; });
  s = s.replace(/ deck (\d{1,2})(?= )/g, ' @deck:$1');
  s = s.replace(RX.myCabin, '$1@mycabin');
  s = s.replace(/ (to|near|from|by|for) me(?= $)/g, ' $1 @here');
  s = s.replace(RX.here, '$1@here');
  s = s.replace(/ (?:too|tu)(?= )/g, ' to');
  return trim(s);
}

// Cut before a strong trigger in mid-sentence ("... escape room how do I get").
function splitClauses(s) {
  var parts = [], last = 0, m;
  RX.starter.lastIndex = 0;
  while ((m = RX.starter.exec(s)) !== null) {
    var at = m.index;
    if (RX.starter.lastIndex === at) {
      RX.starter.lastIndex++;
    }
    if (at === 0) {
      continue;
    }
    var prev = s.slice(0, at).split(' ').pop();
    var next = s.slice(at + m[0].length).split(' ')[0];
    if (prev === 'iam' || prev === 'i' || prev === 'we' ||
        ((prev === 'the' || prev === 'is') && (next === 'closest' || next === 'nearest'))) {
      continue;
    }
    parts.push(s.slice(last, at));
    last = at + m[0].length;
  }
  parts.push(s.slice(last));
  return parts.map(trim).filter(function(p) { return p; });
}

// Transcript -> clauses [{text, correction}].
function normalise(raw, isCabin) {
  var clauses = [];
  clean(raw).split(/[.?!;:\u2026]+(?=\s|$)/).forEach(function(sen) {
    sen = words(sen);
    if (!sen) {
      return;
    }
    RX.contractions.forEach(function(p) { sen = trim(sen.replace(p[0], p[1])); });
    sen = numbers(sen, isCabin);
    // A correction word at the start flags the sentence; one inside splits it.
    var pieces = [], corr = false, m;
    if ((m = sen.match(RX.correctionStart))) {
      corr = true;
      sen = trim(sen.slice(m[0].length));
    }
    while ((m = RX.correction.exec(sen)) !== null && m.index > 0) {
      var after = trim(sen.slice(m.index + m[0].length));
      if (!after) {
        break;
      }
      pieces.push({text: sen.slice(0, m.index), correction: corr});
      corr = true;
      sen = after;
    }
    pieces.push({text: sen, correction: corr});
    pieces.forEach(function(p) {
      splitClauses(categories(stripFillers(p.text), isCabin)).forEach(function(c, k) {
        clauses.push({text: c, correction: p.correction && k === 0});
      });
    });
  });
  return clauses;
}

// ------------------------------------------------------------------ venue lexicon

// A phrase with spaces, "the" and punctuation gone: "The Wind Jammer" ->
// "windjammer". The generator squashes the lexicon with this same function.
function squash(s) {
  var w = numbers(words(clean(s)), function() { return false; });
  return (' ' + w + ' ').replace(/ the(?= )/g, ' ').replace(/theatre/g, 'theater').replace(/centre/g, 'center')
    .replace(/[^a-z0-9|]/g, '');
}

// Optimal string alignment distance (edits, with swaps), stopping past max.
function distance(a, b, max) {
  if (Math.abs(a.length - b.length) > max) {
    return max + 1;
  }
  var d = [], i, j;
  for (i = 0; i <= a.length; i++) {
    d[i] = [i];
  }
  for (j = 0; j <= b.length; j++) {
    d[0][j] = j;
  }
  for (i = 1; i <= a.length; i++) {
    var low = max + 1;
    for (j = 1; j <= b.length; j++) {
      var c = a[i - 1] === b[j - 1] ? 0 : 1;
      var v = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + c);
      if (i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) {
        v = Math.min(v, d[i - 2][j - 2] + 1);
      }
      d[i][j] = v;
      low = Math.min(low, v);
    }
    if (low > max) {
      return max + 1;
    }
  }
  return d[a.length][b.length];
}

var matchers = {};

// match(span, deck) -> {t: target name, i: index, flags, how: 'exact' | 'part' |
// 'fuzzy'} or null. Matching order:
//  1. the whole span, with the deck said ("main dining room" + 5), then as is,
//     then without a final s;
//  2. the longest run of words that is a phrase, when the rest is only noise
//     words or 3 letters ("the wind jam are", "the Cartier store");
//  3. fuzzy, 5+ letters, only when one target is clearly closest: most of one
//     target's phrase (70%+), 1 edit (5-7 letters) or 2 (8+), or a 7+ letter
//     phrase followed by up to 3 letters of noise.
function makeMatcher(lex) {
  var map = {};
  var keys = [];
  function put(k, i) {
    if (k && !Object.prototype.hasOwnProperty.call(map, k)) {
      map[k] = i;
      keys.push(k);
    }
  }
  // Stored phrases first: a group's phrase ("arcade") beats a member's name.
  lex.t.forEach(function(name, i) {
    (lex.p[i] ? lex.p[i].split('|') : []).forEach(function(k) { put(k, i); });
  });
  lex.t.forEach(function(name, i) {
    if (name.indexOf('|') === -1) {
      put(squash(name), i);
    }
  });
  function hit(i, how) {
    return {t: lex.t[i], i: i, flags: lex.f[i] || '', how: how};
  }
  function exact(c) {
    if (Object.prototype.hasOwnProperty.call(map, c)) {
      return map[c];
    }
    if (c.length >= 6 && c.charAt(c.length - 1) === 's' && Object.prototype.hasOwnProperty.call(map, c.slice(0, -1))) {
      return map[c.slice(0, -1)];
    }
    return -1;
  }
  function unique(list) {
    var t = -1;
    for (var i = 0; i < list.length; i++) {
      if (t !== -1 && map[list[i]] !== t) {
        return -1;
      }
      t = map[list[i]];
    }
    return t;
  }
  function fuzzy(c) {
    if (c.length < 5) {
      return -1;
    }
    // A clipped name: most of a phrase ("splashawayb"), from one target only
    // ("solar" could be Solarium, Solarium Bar or Solarium Bistro: none).
    var starts = keys.filter(function(k) { return k.indexOf(c) === 0; });
    if (starts.length) {
      var most = starts.every(function(k) { return c.length >= 0.7 * k.length; });
      return most ? unique(starts) : -1;
    }
    var max = c.length >= 8 ? 2 : 1;
    var best = -1, bestD = max + 1, second = max + 2;
    keys.forEach(function(k) {
      var d = distance(c, k, max + 1);
      if (d < bestD) {
        if (best !== -1 && map[k] !== best) {
          second = bestD;
        }
        best = map[k];
        bestD = d;
      } else if (map[k] !== best && d < second) {
        second = d;
      }
    });
    if (best !== -1 && bestD <= max && second > bestD) {
      return best;
    }
    return unique(keys.filter(function(k) { return k.length >= 7 && c.indexOf(k) === 0 && c.length - k.length <= 3; }));
  }
  return function(span, deck) {
    var c = squash(span || '');
    if (!c) {
      return null;
    }
    var i = deck ? exact(c + deck) : -1;
    if (i === -1) {
      i = exact(c);
    }
    if (i !== -1) {
      return hit(i, 'exact');
    }
    var w = words(clean(span)).split(' ');
    for (var len = w.length - 1; len >= 1; len--) {
      for (var s = 0; s + len <= w.length; s++) {
        var rest = w.slice(0, s).concat(w.slice(s + len));
        var left = rest.join('');
        var noise = rest.every(function(x) { return NOISE[x] || x === 'the'; }) || (left.length <= 3 && !/\d/.test(left));
        var k = noise ? exact(squash(w.slice(s, s + len).join(' '))) : -1;
        if (k !== -1) {
          return hit(k, 'part');
        }
      }
    }
    i = fuzzy(c);
    return i === -1 ? null : hit(i, 'fuzzy');
  };
}

function matcher(ship) {
  ship = ship || 'HM';
  if (!matchers[ship]) {
    matchers[ship] = DATA[ship] ? makeMatcher(DATA[ship]) : function() { return null; };
  }
  return matchers[ship];
}

// ------------------------------------------------------------------ clauses

function cleanSpan(s) {
  s = trim(s || '');
  var changed = true;
  while (changed) {
    changed = false;
    LEAD.forEach(function(l) {
      if (s.indexOf(l + ' ') === 0) {
        s = s.slice(l.length + 1);
        changed = true;
      }
    });
    TAIL.forEach(function(t) {
      t = ' ' + t;
      if (s.length > t.length && s.slice(-t.length) === t) {
        s = s.slice(0, -t.length);
        changed = true;
      }
    });
    if (s === '@here') {
      return s;
    }
  }
  return trim(s);
}

// "main dining room on @deck:5" -> {span: 'main dining room', deck: 5}.
function deckHint(span) {
  var m = span.match(/^(.+?) (?:on|at) @deck:(\d{1,2})$/);
  if (m) {
    return {span: m[1], deck: +m[2]};
  }
  m = span.match(/^@deck:(\d{1,2}) (?:near|by|at|next to|on|in) (.+)$/);
  return m ? {span: m[2], deck: +m[1]} : {span: span, deck: null};
}

// Category requests (owner, 2026-09-28; voice only): a span that asks for any
// bar, any coffee, or a bite to eat, not a named venue.
// - CLOSEST_BAR: the nearest bar flagged B, found like the nearest restroom.
//   "Schooner Bar", "Sand Bar" and "the pub" (Boot & Bonnet Pub) stay venues;
//   "wine bar" has two candidates and is left to the venue matcher.
// - CLOSEST_COFFEE: the nearest place flagged C (Starbucks, Cafe Promenade,
//   Park Cafe). "Starbucks" said by name stays a venue.
// - SNACK: Cafe Promenade, open 24 hours (owner), for a snack or a bite
//   outside dining hours. "Pizza" stays Sorrento's.
var PLACE_FOR = '(?:(?:place|spot|somewhere|where)(?: (?:i|we) can)?(?: to| for)?' +
  '(?: (?:get|grab|have|buy|order|find))?(?: (?:a|an|some|me a|me some))? )?';
var CATEGORY_SPANS = [
  {intent: 'CLOSEST_BAR', what: 'bar', rx: new RegExp('^(?:(?:the|a|an|any|some) )?(?:(?:closest|nearest|close|near|nearby|next|good) )?' +
    PLACE_FOR + '(?:bars?|drinks?|cocktails?|beers?|(?:a )?glass of wine|booze|alcohol|(?:a )?margarita|(?:a )?mojito)' +
    '(?: (?:near @here|near me|nearby|around here|close by))?$')},
  {intent: 'CLOSEST_COFFEE', what: 'coffee', rx: new RegExp('^(?:(?:the|a|an|any|some) )?(?:(?:closest|nearest|close|near|nearby|next|good) )?' +
    PLACE_FOR + '(?:(?:cup of )?coffee|coffee shop|coffee place|cafe|latte|espresso|cappuccino|iced coffee|caffeine)' +
    '(?: (?:near @here|near me|nearby|around here|close by))?$')},
  {intent: 'SNACK', what: 'snack', rx: new RegExp('^(?:(?:the|a|an|any|some) )?(?:(?:closest|nearest|close|near|nearby|next|late night|24 hour|twenty four hour) )?' +
    PLACE_FOR + '(?:snacks?|(?:quick |late night )?(?:bite|food|eats?)(?: to eat)?|something (?:to eat|small)|eat|(?:a )?sandwich|(?:a )?cookie|midnight snack|(?:i am|iam|im) hungry|hungry|starving)' +
    '(?: (?:near @here|near me|nearby|around here|close by|now|right now|at night|late))?$')}
];
var SNACK_PLACE = 'Cafe Promenade';

// Which category a span asks for (CATEGORY_SPANS entry), or null.
function categoryOf(v) {
  if (!v) {
    return null;
  }
  for (var i = 0; i < CATEGORY_SPANS.length; i++) {
    if (CATEGORY_SPANS[i].rx.test(v)) {
      return CATEGORY_SPANS[i];
    }
  }
  return null;
}

// A whole request the route patterns don't catch ("where can we get drinks",
// "I could use a coffee", "I'm hungry").
var CATEGORY_LEAD = /^(?:(?:where|how) (?:can|could|do|would) (?:i|we) |(?:i|we) (?:need|want|would like|could use|could go for) |(?:lets|let us) )?(?:(?:go )?(?:get|grab|find|buy|order|have) )?/;

function categoryRequest(v) {
  return v ? categoryOf(v) || categoryOf(v.replace(CATEGORY_LEAD, '')) : null;
}

function refusedReason(v) {
  var cat = categoryOf(v);
  if (cat && cat.intent !== 'SNACK') {
    return cat.what;  // many bars, many coffee places
  }
  if (/^@restroom/.test(v || '')) {
    return 'restroom';
  }
  if (/^@(?:elevator|forelev|aftelev)/.test(v || '')) {
    return 'elevator';
  }
  if (/^@stairs/.test(v || '')) {
    return 'stairs';
  }
  return /^@deck:/.test(v || '') ? 'deck' : null;
}

function refused(v) {
  return {intent: 'LOCATION_REFUSED', A: v, reason: refusedReason(v)};
}

function locationSpan(rest) {
  var s = rest, moved = true;
  while (moved) {
    moved = false;
    G.locationAdverbs.forEach(function(a) {
      if (s.indexOf(a + ' ') === 0) {
        s = s.slice(a.length + 1);
        moved = true;
      }
    });
  }
  if (s === '@mycabin') {
    return s;
  }
  for (var j = 0; j < G.locationPreps.length; j++) {
    var p = G.locationPreps[j];
    if (s === p) {
      return '';
    }
    if (s.indexOf(p + ' ') === 0) {
      return s.slice(p.length + 1);
    }
  }
  return null;
}

function setLocation(span) {
  var to = trim(span).match(/^(.+?) to (.+)$/);
  if (to) {
    return {intent: 'ROUTE_COMBINED', A: cleanSpan(to[1]), B: cleanSpan(to[2])};
  }
  var d = deckHint(cleanSpan(span));
  if (!d.span || d.span === '@here') {
    return {intent: 'INCOMPLETE'};
  }
  return {intent: 'SET_LOCATION', A: d.span, deck: d.deck};
}

function stripTrigger(c) {
  for (var i = 0; i < RX.route.length; i++) {
    var m = c.match(RX.route[i]);
    if (m) {
      return {rest: trim(c.slice(m[0].length)), where: anyTest(RX.where, c)};
    }
  }
  return null;
}

// Splits what follows a trigger into A and B, first pattern wins.
function routeRest(rest) {
  var m;
  rest = rest.replace(/^(?:over to|up to|down to|back to|the way to|the way) /, 'to ');
  if ((m = rest.match(/^from (.+?) (?:to|towards|toward) (.+)$/)) || (m = rest.match(/^(?:for|front|form|fro) (.+?) to (.+)$/))) {
    return {A: m[1], B: m[2]};
  }
  if ((m = rest.match(/^(?:(?:to|towards|toward|into|for) )?(.+?) (?:from|starting from|starting at|coming from|leaving from|leaving) (.+)$/))) {
    return {A: m[2], B: m[1]};
  }
  if ((m = rest.match(/^from (.+)$/))) {
    return {A: m[1], B: ''};
  }
  if ((m = rest.match(/^(?:to|towards|toward|into|for) (.+)$/))) {
    return {A: null, B: m[1]};
  }
  if ((m = rest.match(/^(.+?) to (.+)$/))) {
    return {A: m[1], B: m[2]};
  }
  return {A: null, B: /^(?:to|towards|toward|into|for)$/.test(rest) ? '' : rest};
}

function restroomClause(c) {
  if (/(?:^| )(?:from|leaving|starting at) (?:the |a )?@restroom(?: |$)/.test(c)) {
    return refused('@restroom');
  }
  var loc = c.match(/^iam (.*)$/);
  var sp = loc ? locationSpan(loc[1]) : null;
  if (sp !== null && /@restroom/.test(sp)) {
    return refused('@restroom');
  }
  var t = stripTrigger(c);
  var s = t ? t.rest : c;
  var m, A = null;
  if ((m = s.match(/@restroom (?:from|near|by|to|next to|close to|closest to|nearest to|around|at|in|on|for|off|nearby) (.+)$/)) ||
      (m = s.match(/(?:^| )(?:from|at|near|by) (.+?) (?:to|towards) (?:the |a )?(?:closest |nearest )?@restroom/)) ||
      (m = s.match(/^(.+?) (?:to|towards) (?:the |a )?(?:closest |nearest )?@restroom/))) {
    A = cleanSpan(m[1]);
  }
  if (A === '@here') {
    A = null;
  }
  var d = A ? deckHint(A) : {span: null, deck: null};
  var dm = /^@deck:(\d{1,2})$/.exec(d.span || '');
  if (dm) {
    return {intent: 'CLOSEST_RESTROOM', A: null, deck: +dm[1]};  // "closest restroom on deck 5": a hint
  }
  if (refusedReason(d.span)) {
    return refused(d.span);
  }
  return {intent: 'CLOSEST_RESTROOM', A: d.span, deck: d.deck};
}

// One clause -> intent with slot spans (not matched yet).
function parseClause(c) {
  var m, i;
  if (anyTest(RX.stateroom, c)) {
    return {intent: 'OUT_OF_SCOPE_KNOWN', topic: 'stateroom'};
  }
  if (anyTest(RX.hours, c)) {
    return {intent: 'OUT_OF_SCOPE_KNOWN', topic: 'hours'};
  }
  if (anyTest(RX.schedule, c)) {
    return {intent: 'OUT_OF_SCOPE_KNOWN', topic: 'schedule'};
  }
  if (/@restroom/.test(c)) {
    return restroomClause(c);
  }
  if ((m = c.match(/^iam (.*)$/))) {
    var span = locationSpan(m[1]);
    if (span !== null) {
      return span === '' ? {intent: 'INCOMPLETE'} : setLocation(span);
    }
  }
  if ((m = c.match(/^(?:currently |now )?(at|near|outside|next to|in) (.+)$/)) && !/ to /.test(m[2])) {
    return setLocation(m[2]);
  }
  for (i = 0; i < RX.locOther.length; i++) {
    if ((m = c.match(RX.locOther[i]))) {
      return setLocation(m[1] || m[2] || '');
    }
  }
  var t = stripTrigger(c);
  var r;
  if (t) {
    if (!t.rest) {
      return anyTest(RX.back, c) ? {intent: 'ROUTE', A: null, B: '@mycabin', trigger: true} : {intent: 'INCOMPLETE'};
    }
    r = routeRest(t.rest);
    if (t.where) {
      r.B = (r.B || '').replace(/ (?:on|located|at)$/, '');
    }
  } else {
    r = routeRest(c);
  }
  var A = r.A === null ? null : cleanSpan(r.A);
  var B = cleanSpan(r.B);
  if (A === '@here') {
    A = null;
  }
  if (!B || B === 'there' || B === '@here') {
    return {intent: 'INCOMPLETE'};
  }
  if (B === 'back' || B === 'back home') {
    B = '@mycabin';
  }
  var dA = A ? deckHint(A) : {span: null, deck: null};
  var dB = deckHint(B);
  if (refusedReason(dA.span)) {
    return refused(dA.span);
  }
  return {intent: 'ROUTE', A: dA.span, B: dB.span, deckA: dA.deck, deck: dB.deck, trigger: !!t, bare: !t && r.A === null};
}

// ------------------------------------------------------------------ resolve

var BANK_TARGETS = {'@forelev': 'Fore elevators', '@aftelev': 'Aft elevators'};  // directory places

function cabinOf(v) {
  var m = /^@cabin:(\d+)$/.exec(v || '');
  return m ? m[1] : null;
}

function special(v) {
  return /^@/.test(v || '');
}

// Matches a clause's spans against the lexicon.
function resolve(p, match) {
  if (!p) {
    return p;
  }
  function target(v, deck) {
    if (!v) {
      return null;
    }
    if (BANK_TARGETS[v]) {
      return {t: BANK_TARGETS[v], flags: '', how: 'exact'};
    }
    return special(v) ? null : match(v, deck);
  }
  var out = {intent: p.intent, A: p.A || null, B: p.B || null, reason: p.reason, topic: p.topic, deck: p.deck};
  out.cabin = cabinOf(out.A) || cabinOf(out.B);
  if ((p.intent === 'SET_LOCATION' || p.intent === 'ROUTE_COMBINED') && refusedReason(out.A)) {
    return refused(out.A);
  }
  if ((p.intent === 'ROUTE' || p.intent === 'ROUTE_COMBINED') && out.B === '@restroom') {
    out.intent = 'CLOSEST_RESTROOM';
    out.B = null;
  }
  if (p.intent === 'ROUTE' && out.A && out.B && !special(out.A) && !target(out.A) &&
      categoryRequest(out.A + ' to ' + out.B)) {
    // Split at "to": "closest place to get a drink", "something to eat".
    out.B = out.A + ' to ' + out.B;
    out.A = null;
    p = copy(p);
    p.bare = true;
  }
  var cat = (p.intent === 'ROUTE' || p.intent === 'ROUTE_COMBINED') ?
    categoryOf(out.B) || (p.bare ? categoryRequest(out.B) : null) : null;
  if (cat && cat.intent === 'SNACK') {
    // A bite outside dining hours: Cafe Promenade, open 24 hours.
    out.via = 'snack';
    out.B = SNACK_PLACE.toLowerCase();
  } else if (cat) {
    // The nearest bar or coffee place, found by the route planner like the nearest restroom.
    out.intent = cat.intent;
    out.B = null;
  }
  var a = target(out.A, p.deckA || (p.intent !== 'ROUTE' ? p.deck : null));
  if (p.intent === 'SET_LOCATION' && out.A && !special(out.A) && !a) {
    // "I'm at the bar next to the Solarium": the named side.
    var two = out.A.match(/^(.+?) (?:near|by|next to|beside|outside|at|in front of) (.+)$/);
    if (two) {
      var right = target(cleanSpan(two[2])), left = target(cleanSpan(two[1]));
      if (right) {
        out.A = cleanSpan(two[2]);
        a = right;
      } else if (left) {
        out.A = cleanSpan(two[1]);
        a = left;
      }
    }
  }
  var b = target(out.B, p.deck);
  var unresolved = function(v, t) { return v && !special(v) && !t; };
  if (out.intent === 'ROUTE' && !out.A && unresolved(out.B, b)) {
    // "to" dropped: "Boardwalk the Solarium".
    var w = out.B.split(' ');
    for (var k = 1; k < w.length; k++) {
      var ta = target(cleanSpan(w.slice(0, k).join(' '))), tb = target(cleanSpan(w.slice(k).join(' ')));
      if (ta && tb && ta.how !== 'fuzzy' && tb.how !== 'fuzzy') {
        out.A = cleanSpan(w.slice(0, k).join(' '));
        out.B = cleanSpan(w.slice(k).join(' '));
        a = ta;
        b = tb;
        break;
      }
    }
  }
  if (unresolved(out.A, a) || unresolved(out.B, b)) {
    if (!p.bare && RX.event.test((out.A || '') + ' ' + (out.B || ''))) {
      return {intent: 'OUT_OF_SCOPE_KNOWN', topic: 'schedule', A: out.A, B: out.B, cabin: out.cabin};
    }
    return {intent: 'NO_MATCH', reason: p.bare ? 'no_command' : 'no_place', A: out.A, B: out.B, cabin: out.cabin};
  }
  // A bare phrase ("Play some music") only counts when it matched outright.
  if (p.bare && b && b.how !== 'exact') {
    return {intent: 'NO_MATCH', reason: 'no_command', A: out.A, B: out.B, cabin: out.cabin};
  }
  if ((a && a.flags.indexOf('N') !== -1) || (b && b.flags.indexOf('N') !== -1)) {
    return {intent: 'NO_MATCH', reason: 'not_mapped', A: out.A, B: out.B, cabin: out.cabin,
            A_target: a ? a.t : null, B_target: b ? b.t : null};
  }
  if (out.intent === 'SET_LOCATION' && a && (/[LA]/.test(a.flags) || a.t.indexOf('|') !== -1)) {
    // Not one spot: several spots, ashore, or a group ("I'm at the arcade": which one?).
    return {intent: 'LOCATION_REFUSED', A: out.A, A_target: a.t,
            reason: a.flags.indexOf('A') !== -1 ? 'ashore' : a.flags.indexOf('L') !== -1 ? 'multi_spot' : 'group'};
  }
  out.A_target = a ? a.t : null;
  if (a && (/[LA]/.test(a.flags) || a.t.indexOf('|') !== -1)) {
    // A start that isn't one spot (voicecard.js refuses it as a start, §9.6).
    out.A_spot = a.flags.indexOf('A') !== -1 ? 'ashore' : a.flags.indexOf('L') !== -1 ? 'multi_spot' : 'group';
  }
  out.B_target = b ? b.t : null;
  out.A_how = a ? a.how : null;
  out.B_how = b ? b.how : null;
  out.bare = p.bare;
  return out;
}

// ------------------------------------------------------------------ merge

var IN_SCOPE = {SET_LOCATION: 1, ROUTE: 1, ROUTE_COMBINED: 1, CLOSEST_RESTROOM: 1, CLOSEST_BAR: 1, CLOSEST_COFFEE: 1,
                LOCATION_REFUSED: 1};

// Several clauses -> one result (voice-commands.json slot_rules).
function merge(items, match) {
  var res = [];
  items.forEach(function(it) {
    if (!it.r) {
      return;
    }
    // A correction that is only a place replaces the previous result's last slot.
    var prev = res[res.length - 1];
    var bare = it.correction && it.p.intent === 'ROUTE' && it.p.bare ? it.p.B : null;
    if (bare && prev && IN_SCOPE[prev.p.intent]) {
      var p2 = copy(prev.p);
      p2[prev.p.intent === 'ROUTE' || prev.p.intent === 'ROUTE_COMBINED' ? 'B' : 'A'] = bare;
      res[res.length - 1] = {p: p2, r: resolve(p2, match)};
      return;
    }
    res.push(it);
  });
  // A bare place followed by a route without A: that place is A.
  for (var i = 0; i + 1 < res.length; i++) {
    var a = res[i].r, b = res[i + 1].r;
    if (a.intent === 'ROUTE' && a.bare && !a.A && b.intent === 'ROUTE' && !b.A) {
      var p3 = copy(res[i + 1].p);
      p3.A = a.B;
      res.splice(i, 2, {p: p3, r: resolve(p3, match)});
      i--;
    }
  }
  var rs = res.map(function(x) { return x.r; });
  var loc = null, act = null, refusal = null, last = null;
  rs.forEach(function(r) {
    if (IN_SCOPE[r.intent]) {
      last = r;
      if (r.intent === 'SET_LOCATION') {
        loc = r;
      } else if (r.intent === 'LOCATION_REFUSED') {
        refusal = r;
      } else {
        act = r;
      }
    }
  });
  if (act && loc && !act.A && (act.intent === 'ROUTE' || act.intent === 'CLOSEST_RESTROOM' ||
                             act.intent === 'CLOSEST_BAR' || act.intent === 'CLOSEST_COFFEE')) {
    var c = copy(act);
    c.A = loc.A;
    c.A_target = loc.A_target;
    c.A_how = loc.A_how;
    c.cabin = act.cabin || loc.cabin;
    c.A_spot = loc.A_spot;
    c.atA = true;  // A came from "I'm at": it also sets the spoken start (D4)
    if (act.intent === 'ROUTE') {
      c.intent = 'ROUTE_COMBINED';
    }
    return c;
  }
  if (refusal && act && !act.A) {
    return refusal;
  }
  if (last) {
    return last;
  }
  var order = ['OUT_OF_SCOPE_KNOWN', 'INCOMPLETE'];
  for (var k = 0; k < order.length; k++) {
    var of = rs.filter(function(r) { return r.intent === order[k]; });
    if (of.length) {
      return of[of.length - 1];
    }
  }
  return rs.length ? rs[rs.length - 1] : {intent: 'NO_MATCH', reason: 'empty'};
}

function parse(text, opts) {
  opts = opts || {};
  var isCabin = opts.isCabin || function() { return false; };
  var match = matcher(opts.ship);
  var items = normalise(text, isCabin).map(function(c) {
    var p = parseClause(c.text);
    return {p: p, r: resolve(p, match), correction: c.correction};
  });
  var r = merge(items, match);
  var out = {intent: r.intent, A: r.A || null, B: r.B || null, cabin: r.cabin || null,
             A_target: r.A_target || null, B_target: r.B_target || null, A_how: r.A_how || null, B_how: r.B_how || null};
  if (r.intent === 'ROUTE_COMBINED') {
    r.atA = true;
  }
  ['reason', 'topic', 'deck', 'via', 'A_spot', 'atA'].forEach(function(k) {
    if (r[k]) {
      out[k] = r[k];
    }
  });
  if (out.intent === 'OUT_OF_SCOPE_KNOWN' || out.intent === 'INCOMPLETE' || (out.intent === 'NO_MATCH' && out.reason !== 'not_mapped')) {
    out.A_target = out.B_target = out.A_how = out.B_how = null;
  }
  return out;
}

// The places a category request chooses from (flags in the generated lexicon:
// B bars, C coffee); the route planner picks the nearest, like the nearest restroom.
function flagged(ship, flag) {
  var d = DATA[ship || 'HM'];
  if (!d) {
    return [];
  }
  return d.t.filter(function(t, i) { return (d.f[i] || '').indexOf(flag) !== -1; });
}

function bars(ship) {
  return flagged(ship, 'B');
}

function coffee(ship) {
  return flagged(ship, 'C');
}

module.exports = {
  parse: parse,
  bars: bars,
  coffee: coffee,
  normalise: normalise,
  matcher: matcher,
  makeMatcher: makeMatcher,
  squash: squash,
  GRAMMAR: GRAMMAR
};
