// Bundles the open source conflicts for the settings page's Map check card
// (docs/PROJECT_BRIEF.md, "Map check"). Run from the repo root after changing
// tools/shipmap/conflicts-HM.json:
//   node tools/shipmap/build_conflicts.js
// test/pkjs/shipmap-data.test.js checks the output is up to date.
var fs = require('fs');
var path = require('path');

var SHIPS = ['HM'];
var ROOT = path.join(__dirname, '..', '..');

// What the card needs from each open entry: the question and what each source says.
function build(ship) {
  var file = JSON.parse(fs.readFileSync(path.join(__dirname, 'conflicts-' + ship + '.json'), 'utf8'));
  var open = file.conflicts.filter(function(c) { return c.status === 'open'; }).map(function(c) {
    var out = {id: c.id, kind: c.kind, check: c.check, svg: c.svg, app: c.app, using: c.using};
    if (c.venues) {
      out.venues = c.venues;
    }
    if (c.deck) {
      out.deck = c.deck;
    }
    return out;
  });
  return '// Generated by tools/shipmap/build_conflicts.js from tools/shipmap/conflicts-' + ship +
    '.json (open entries only). Do not edit by hand.\n' +
    'module.exports = ' + JSON.stringify({ship: ship, conflicts: open}) + ';\n';
}

if (require.main === module) {
  SHIPS.forEach(function(ship) {
    var out = path.join(ROOT, 'src', 'pkjs', 'data', 'conflicts-' + ship + '.js');
    fs.writeFileSync(out, build(ship), 'utf8');
    console.log('Wrote ' + path.relative(ROOT, out));
  });
}

module.exports = {build: build};
